# Generated by Django 3.1.2 on 2020-12-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('num_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateTimeField(auto_now_add=True)),
                ('date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('updated_issue', models.DateTimeField(auto_now=True)),
                ('costumer_name', models.TextField()),
                ('costumer_address', models.TextField()),
                ('closed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        
        migrations.CreateModel(
            name='LineReceipt',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, default=1, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipt.factura')),
            ],
        ),
    ]