# Generated by Django 3.1.2 on 2020-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_linereceipt_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='costumer_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='costumer_name',
            field=models.TextField(),
        ),
    ]