# Generated by Django 3.1.2 on 2020-12-06 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20201206_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='year',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]