# Generated by Django 3.1.2 on 2020-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20201206_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]