# Generated by Django 3.1.2 on 2020-12-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_auto_20201206_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linereceipt',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
