# Generated by Django 3.1.2 on 2020-12-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_auto_20201206_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='linereceipt',
            name='receipt',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='factura.receipt'),
        ),
    ]
