# Generated by Django 3.1.2 on 2020-12-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_auto_20201206_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linereceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.receipt'),
        ),
    ]
