# Generated by Django 3.1.2 on 2020-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_auto_20201206_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linereceipt',
            name='id_product',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='linereceipt',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='linereceipt',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='linereceipt',
            name='units',
            field=models.IntegerField(default=1, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='costumer_address',
            field=models.TextField(verbose_name='Dirección del cliente'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='costumer_name',
            field=models.TextField(verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='num_receipt',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='year',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Año'),
        ),
    ]
